### ISSUE TITLE
Multiverse-CoreとMultiverse-Portals

### ISSUE THREAD

**Issue by reokunchan** [playerrealms/PluginRequest#10]
1つのサーバーで複数のワールドを管理できる(Multiverse-Core)。また、ゲートを作成しワールドを移動することができる(Multiverse-Portals)。

CoreのほうのURL: https://dev.bukkit.org/projects/multiverse-core
PortalsのほうのURL: https://dev.bukkit.org/projects/multiverse-portals

**Comment by yuki0308** [comment]
MultiverseはUltraPremiumのサーバーで使用することが可能になっています。

**Comment by PlayerRealmsCommunity** [comment]
CoreはUltraPremiumで使用可能ですが、Portalsはないので追加してほしいです。

**Comment by yuki0308** [comment]
追加しました
