### ISSUE TITLE
話し合いの末の追加希望プラグイン

### ISSUE THREAD

**Issue by PlayerRealmsCommunity** [playerrealms/PluginRequest#13]
FarmProtect
https://dev.bukkit.org/projects/farmprotect
FrameProtect
https://dev.bukkit.org/projects/frameprotect
RemoteToolKit
https://www.spigotmc.org/resources/minecraft-remote-toolkit-for-1-10-1-11-x.29777/
Rtrigger
https://dev.bukkit.org/projects/rtriggers
EasyKits
https://dev.bukkit.org/projects/easykits

**Comment by yuki0308** [comment]
RemoteToolKitは遠隔操作が可能になるプラグインのため、追加はできません。
それ以外のプラグインについては追加しました。
