### ISSUE TITLE
友達の代理で受けた追加してほしいPluginについて

### ISSUE THREAD

**Issue by CodeName-sirokuma** [playerrealms/PluginRequest#14]
Escape The Mob : Mobを動かして逃げるミニゲームプラグインです。(簡単に言えばドラゴンエスケープ)
bukkiturl: https://dev.bukkit.org/projects/escape-mob

Fast Async Worldedit : VoxelSniperとは違い,VoxelやWolrdEditではできないもの、細かいところまで楽にきれいにできるそうです。
spigotulr : https://www.spigotmc.org/resources/fast-async-worldedit-voxelsniper.13932/
前回の「survivalgame」のPluginと一緒に検討お願いします。(連続投稿すいません)

**Comment by yuki0308** [comment]
Escape The Mob
このプラグインはSpigotに対応してないと思われるので、導入は見送りになります。
Fast Async Worldedit
このプラグインについては既に導入済みとなっていますが、UltraPremiumのみとなっています。

**Comment by CodeName-sirokuma** [comment]
ありがとうございます^^
