### ISSUE TITLE
Fast Async World Edit&Voxel Sniper

### ISSUE THREAD

**Issue by kama6012** [PlayerRealms/PluginRequest#15]
Presently,only ultra premium server can use "Fast Async World Edit".
But it's important to reduce server lag with asynchronous processing.
Today,server lag is very big problem in Player Realms.
So I think it is better to allow FAWE every people.
Please tell me your opinion.

(日本語でissueを書くのも許可してほしいです、英語は結構面倒なので。)

**Comment by yuki0308** [comment]
これについては自分も同じこと考えてるけどBowserにも聞いてみないとだめだから様子見
