### ISSUE TITLE
WildSkript(fork)

### ISSUE THREAD

**Issue by kama6012** [playerrealms/PluginRequest#2]
URL https://forums.skunity.com/resources/fork-of-wildskript-1-9-1-10.101/

Description
Addon of Skript. Customize your server's recipe, holograms, scoreboard and tab with the detailed settings.

**Comment by yuki0308** [comment]
リンク切れしてるから別のURLを張ってね

**Comment by kama6012** [comment]
URL切れしていないWildSkriptがなかったのでCloseします
--Closed--
