### ISSUE TITLE
Please add Vixio :)

### ISSUE THREAD

**Issue by MIrAgEdayo** [PlayerRealms/PluginRequest#22]
Skriptのアドオン Vixioの実装を望んでいます
私が企画しているシステムで、他のユーザーにデータを改変されないよう、Discord上から
データを取得することを目的としています。
よろしくお願いします。

配布ページ: https://www.spigotmc.org/resources/skript-addon-vixio-the-best-discord-addon-on-the-market.34360/updates

**Comment by yuki0308** [comment]
Skriptで通信機能は利用することができないため、Vixioは導入することはできません
