### ISSUE TITLE
Needed Plugins

### ISSUE THREAD

**Issue by RaMenPower** [playerrealms/PluginRequest#3]
Lower the **LibsDisguises**'s grade from Ultra Premium to normal.

**Comment by RaMenPower** [comment]
I want also Vixio.

**Comment by HaruchanJP** [comment]
追加してほしいプラグインはここに送信すればいいのですか？

**Comment by yuki0308** [comment]
新しくissues書いて

**Comment by Modo0305** [comment]
えっとskywarsのPluginがほしいです
https://www.spigotmc.org/resources/skywars.23852/
で
前提に
https://www.spigotmc.org/resources/minigameslib.23844/
が必要なのでいれてほしいです
