### ISSUE TITLE
To play murder

### ISSUE THREAD

**Issue by RaMenPower** [playerrealms/PluginRequest#5]
We don't have enough plugins to use plugin,"Murder". https://www.spigotmc.org/resources/murder.1052/
We need:
**NickNamer** https://www.spigotmc.org/resources/nicknamer-integrated-api.5341/?ref=spiget
**MenuBuilder** https://www.spigotmc.org/resources/api-menubuilder.12995/?ref=spiget
**ResourcePackAPI** https://www.spigotmc.org/resources/api-resourcepackapi-1-7-1-8-1-9-1-10.2397/?ref=spiget
**NPCLib** https://www.spigotmc.org/resources/api-npclib.5853/?ref=spiget

**Comment by yuki0308** [comment]
MenuBuilder
ResourcePackAPI
NPCLib
の3つはサーバーに対応してない可能性があるから見送り
